controllers:
    resource: ../src/Controller/
    type: attribute
saludo_ces:
    path: /saludo
    controller: App\Controller\Saludo::hola
calculadora:
    path: /calculadora
    controller: App\Controller\Calculadora::operar
